### ISSUE TITLE
Riptide server abuse

### ISSUE THREAD

**Issue by Notdbrand** [Lucaslah/WeatherChanger#10]
I am the host of a Minecraft server and a someone is using this mod to to change their client side weather and then use riptide to fly around without having to use rockets and at insane speeds, giving them a massive advantage. Is there anyway to stop this.

**Comment by Lucaslah** [comment]
Hi @Notdbrand I'll defiantly look into this, thanks for reporting.

**Comment by Lucaslah** [comment]
@Notdbrand this has been fixed in [Weather Changer 1.2.0](https://github.com/Lucaslah/WeatherChanger/releases/tag/1.2.0), however obviously users can just not update to this version to continue using riptide when its not raining, I would recommend you install an anti-cheat to prevents users from doing this.
